server:
  port: 8082

spring:
  application:
    name: HotelService
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      server-url:
        defaultZone: http://localhost:8761/eureka